# Generated by Django 5.0.7 on 2024-07-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование продукта",
                        max_length=50,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Введите описание продукта",
                        max_length=100,
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Прикрепите фото",
                        null=True,
                        upload_to="product/preview",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(blank=True, null=True, verbose_name="Цена"),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product",
                        to="category.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name", "price", "category"],
            },
        ),
    ]
